force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradesController_Test.cls
@isTest
public class TradesController_Test {

    @testSetup
    static void demoTestSetUp(){
        Trade__c newTrade = new Trade__c(Buy_Amount__c=100, 
                                Buy_Currency__c='EUR',
                                Date_Booked__c=Datetime.now(), 
                                Rate__c=1.33,Sell_Amount__c=200, 
                                Sell_Currency__c='USD');
        insert newTrade;
    }
    @isTest
    static void validategetTrades() {
        List<Trade__c> trades = [SELECT  Id,Sell_Currency__c, Sell_Amount__c, Buy_Currency__c, Buy_Amount__c, Rate__c, Date_Booked__c FROM Trade__c];
        system.debug(trades);
        Test.startTest();
        List<Trade__c> checkTrades = TradesController.getTrades();
        Test.stopTest();

        System.assertEquals('USD', checkTrades[0].Sell_Currency__c );
    }
    testMethod static void testCallout() {
        Test.startTest();
         // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new HTTPMockCallout());
        Decimal response = TradesController.makeGetCallout('EUR','USD');
        Test.stopTest();
        System.assertEquals(1.17188, response);
    }
    testMethod static void testCalloutFail() {
       
        try{
        Test.startTest();
         // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new HTTPMockCalloutFail());
        Decimal response = TradesController.makeGetCallout('EUR','USD');
        Test.stopTest();
        }
        catch(Exception e){
        }
    }
}