force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradesController.cls
public without sharing class TradesController {

    //Method used get the Booked Trades
    @AuraEnabled
    public static List<Trade__c> getTrades() {
        return [
            SELECT  Id,Sell_Currency__c, Sell_Amount__c, Buy_Currency__c, Buy_Amount__c, Rate__c, Date_Booked__c 
            FROM Trade__c
        ];
    }
    @AuraEnabled
    public static Decimal makeGetCallout(String valueSellCurrency, String valueBuyCurrency) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String Url='http://data.fixer.io/api/';
        String endpoint = 'latest';
        String access_key = 'a4d185605657542cc0ab809df043b9d9';  
        request.setEndpoint(Url+endpoint+'?access_key='+access_key+'&base='+valueSellCurrency+'&symbols='+valueBuyCurrency);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        //If the request is successful, parse the JSON response.   
        if(response.getStatusCode() == 200) {
            system.debug(response.getBody());
            Map<String, Object> payload = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            try{
                Map<String, Object> rates = (Map<String, Object>)payload.get('rates'); 
                return (Decimal)rates.get(valueBuyCurrency);
            }catch(Exception e){
                Map<String, Object> error = (Map<String, Object>)payload.get('error'); 
                Decimal errorCode=(Decimal)error.get('code');
                String errorType=(String)error.get('type');
                throw new AuraHandledException('Error '+errorCode+' '+ errorType);
            }
        }
        return null;
        
    }
}